config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "sessions#new"
  get "/login", to: "sessions#new"
  get  "/signup",  to: "users#new"
  post "/signup",  to: "users#create"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  post "/run_project", to: "projects#run_project"
  get "/run_project", to: "projects#run_project_show"
  resources :users do
    resources :projects
  end

  resources :projects do 
    resources :suggestions
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects

  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]

  def show
    @user = User.find(params[:id])
    @projects = @user.projects
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "successfully"
      redirect_to @user
    else
      render 'new'
    end
  end

  private 
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/views/users/_project.html.erb
_project.html.erb

app/views/users/new.html.erb
<!-- <div class="container"> -->
  <%= form_for(@user, url: signup_path, :html => {class: "form"}) do |f| %>
    <h3 class="form-heading">Log in to Resource Allocation App</h3>
    <%= render "shared/error_messages" %>
    <div class="form-field">
      <div class="field">
        <%= f.email_field :email, placeholder: "Email", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.password_field :password, autocomplete: "current-password", 
          class: "form-control", placeholder: "Password"  %>
      </div>

      <div class="field">
        <%= f.password_field :password_confirmation, autocomplete: "current-password", 
          class: "form-control", placeholder: "Password Confirmation"  %>
      </div>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
    <p class="text-center" style="margin-top:10px;">
      or <a href="<%= login_path %>">log in</a>
    </p>
  <% end %>
<!-- </div>  -->

app/views/users/show.html.erb
Welcome <%= @user.name %><br>
<%= link_to "Log out", logout_path, method: :delete %>
<br>
<br>
<% @projects.each do |project| %>
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title project" value="{{$project_id}}">Project - <%= project.name %></h3>
        </div>
        <div class="panel-body">                    
          <div class="col-md-12">
            <table class="table table-striped custab">
              <thead>
               <tr>
                  <th>Project ID</th>
                  <th>Number of task</th>
                  <th>Number of Develop</th>
                  <th>Description</th>
                  <th>Action</th>
              </tr>
            </thead>
              <tr>                           
                <td><%= link_to project.id, user_project_path(@user.id, project.id) %></td>
                <td><%= link_to project.number_of_task, user_project_path(@user.id, project.id)%></td>
                <td><%= link_to project.number_of_develop, user_project_path(@user.id, project.id)%></td>
                <td><%= project.description%></td>
                <td> <%= link_to root_path do %>
                  <i class="fa fa-pencil" aria-hidden="true"></i>
                <% end %>
                <%= link_to root_path do %>
                  <i class="fa fa-trash"></i>
                <% end %>
                </td>   
              </tr>   
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%= button_to new_user_project_path(@user.id), :method => :get, class: "pull-right thumbnail btn-success" do %>
  <i class="fa fa-plus-square" aria-hidden="true"></i> NEW PROJECT
<% end %>
<!-- <button class="pull-right thumbnail btn-success"><i class="fa fa-plus-square" aria-hidden="true"></i> NEW PROJECT</button> -->