config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "sessions#new"
  get "/login", to: "sessions#new"
  get  "/signup",  to: "users#new"
  post "/signup",  to: "users#create"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  post "/run_project", to: "projects#run_project"
  get "/run_project", to: "projects#run_project_show"
  resources :users do
    resources :projects
  end

  resources :projects do 
    resources :suggestions
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :suggestions

  enum strategies: { CREATE: 0, MUTATE: 1, CROSSOVER: 2}
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :logged_in_user

  def index
  end

  def show
    @project = Project.find(params[:id])
    @suggestion = @project.suggestions
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash.now[:success] = "Successfully"
      redirect_to user_path current_user
    else
      flash[:danger] = "Something went wrong"
      render 'new'
    end
  end

  def run_project
    @suggestion = Suggestion.new
    duration = convert_to_arr(params[:duration])
    dependence = convert_to_arr(params[:dependence])
    treq = convert_treq(params[:matrix_experiment])
    lexp = convert_lexp(params[:level_experience])
    weighted_of_fitness_1 = params[:weighted_of_fitness_1]
    weighted_of_fitness_2 = params[:weighted_of_fitness_2]
    get_value(duration, dependence, treq, lexp, weighted_of_fitness_1, weighted_of_fitness_2)
    project_id = params[:project_id].to_i
    @parents1 = get_best(100)
    @parents = @parents1.reverse.paginate(page: params[:page], per_page: 10)
  end

  private
  
  def project_params
    params.require(:project).permit(:user_id, :name, :number_of_task, :number_of_develop,
      :description, :duration, :dependence, :matrix_experiment, :level_experience,
      :weighted_of_fitness_1, :weighted_of_fitness_2)
  end
end

app/views/projects/index.html.erb
index.html.erb

app/views/projects/new.html.erb
<%= form_for @project, url: user_projects_path ,:html => {id: "page-wrapper"} do |f| %>
  <h1>Create New Project</h1>

  <%= f.hidden_field :user_id, value: params[:user_id]  %>
  
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :number_of_task %>
  <%= f.text_field :number_of_task %><br>

  <%= f.label :number_of_develop %>
  <%= f.text_field :number_of_develop %><br>

  <%= f.label :description %>
  <%= f.text_area :description, cols: "70" %><br><br>

  <%= f.label :duration %>
  <%= f.text_area :duration, rows: "5" %>

  <%= f.label :dependence %>
  <%= f.text_area :dependence, rows: "5" %><br><br>

  <%= f.label :matrix_experiment %>
  <%= f.text_area :matrix_experiment, rows: "5" %>

  <%= f.label :level_experience %>
  <%= f.text_area :level_experience, rows: "5" %><br><br>

  <div class="row">
    <div class="col-sm-6">
      <%= f.label :weighted_of_fitness_1 %>
      <%= f.text_field :weighted_of_fitness_1 %>
    </div>
    <div class="col-sm-6">
      <%= f.label :weighted_of_fitness_2 %>
      <%= f.text_field :weighted_of_fitness_2 %>
    </div>

  </div><br>
  
  <%= f.submit "Create", class: "btn btn-primary button1", style: "width: 20px, height: 30px"  %>
  <!-- <div class = "pull-right thumbnail"> -->
  </div>
<% end %>

app/views/projects/run_project.html.erb
<% projectId = params[:project_id] %>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">List Suggestion</h3>
      </div>
      <div class="panel-body">
        <div class="col-md-12">
          <table class="table table-striped custab">
            <thead>
              <tr>
                <th>Index</th>
                <th>Genes</th>
                <th>Fitness</th>
                <th class="text-center">Action</th>
              </tr>
            </thead>
            <%= will_paginate @parents %>
            <% @parents.each do |parent| %>
            <tr>   
              <td><%= @parents1.find_index(parent) %></td>
              <!-- <td id="">1.01</td> -->
              <td id=""><%= parent.genes %></td>
              <td id=""><%= parent.fitness %></td>                            
              <td class="text-center">
                <%= form_for @suggestion, url: project_suggestions_path(project_id: projectId) do |f| %>
                  <%= f.hidden_field :genes, value: parent.genes %>
                  <%= f.hidden_field :fitness, value: parent.fitness %>
                  <%= f.hidden_field :project_id, value: projectId %>
                  <%= f.submit "Save", class: "btn btn-success save" %>
<!--                   <button type="button" class="btn btn-success save" value="{{$s['number']}}">
                      <span class="glyphicon glyphicon-save"></span>Save
                  </button>   -->
                <% end %>                             
              </td>
            </tr>
            <% end %>
          </table>
          <%= will_paginate @parents %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="row" >
  <div class="col-lg-offset-4 col-lg-4 col-sm-4">
    <div class="circle-tile">
      <a href="{{url('admin/projects')}}">
        <div class="circle-tile-heading green">
          <i class="fa fa-archive fa-fw fa-3x"></i>
        </div>
      </a>
      <div class="circle-tile-content green">
        <div class="circle-tile-description text-faded">
          Project 
        </div>
        <div class="circle-tile-number text-faded">
          <%= @project.id %>
          <span id="sparklineA"></span>
        </div>
        <%= link_to run_project_path(duration: @project.duration, dependence: @project.dependence,
          matrix_experiment: @project.matrix_experiment, level_experience: @project.level_experience,
          weighted_of_fitness_1: @project.weighted_of_fitness_1, weighted_of_fitness_2: 
          @project.weighted_of_fitness_2, project_id: @project.id ),
          method: "POST", class: "circle-tile-footer" do %>
          Run Project with GA <i class="fa fa-chevron-circle-right"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class = "container"> 
  <div class="row">
    <div class="col-sm-3">
      <div id = "page-wrapper1">
      <h5>List of duration</h5>
      <%= break_the_lines( @project.duration) %>
      </div>
    </div>
    <div class="col-sm-3">
      <div id = "page-wrapper1">
        <h5>List of Depedences </h5>
        <%= break_the_lines( @project.dependence) %>
      </div>
    </div>
    <div class="col-sm-3">
      <div id = "page-wrapper1">
        <h5>Matrix Experience</h5>
        <%= break_the_lines( @project.matrix_experiment) %>
      </div>
    </div>
    <div class="col-sm-3">
      <div id = "page-wrapper1">
      <h5>Level Experiencee</h5>
      <%= break_the_lines( @project.level_experience) %>
      </div>
    </div>

  </div>
</div>
<!-- <li><%= link_to "Listf Depedences ", "#"%></li>
<li><%= link_to "Matrix Experience ", "#"%></li><br> -->
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title project" value="{{$project_id}}">Project - <%= @project.name  %></h3>
      </div>
      <div class="panel-body">                    
        <div class="col-md-12">
          <table class="table table-striped custab">
            <thead>
             <tr>
                <th>Phase</th>
                <th>Pop'size</th>
                <th>Weighted of Fitness 1 </th>
                <th>Weighted of Fitness 2</th>
            </tr>
          </thead>
          <tr>                           
            <td>100</td>
            <td>100</td>
            <td><%= @project.weighted_of_fitness_2 %></td>
            <td><%= @project.weighted_of_fitness_1 %></td>                            
          </tr>   
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h3 class="panel-title">List Suggestion</h3>
			</div>
			<div class="panel-body">
				<div class="col-md-12">
				  <table class="table table-striped custab">
				    <thead>
				    	<tr>
					      <th>Number</th>                                
					      <!-- <th>Number of Phase</th> -->
					      <th>Genes</th>
					      <th>Fitness</th>
					      <!-- <th class="text-center">Action</th> -->
				    	</tr>
				  	</thead>
				  	<% if @suggestion %>
            <% i = 1 %>
  				  	<% @suggestion.each do |suggestion| %>
  					  <tr>                           
  				      <td><%= i %></td>
  				      <!-- <td id="">500</td> -->
  				      <td id=""><%= suggestion.genes %></td>
  				      <td id=""><%= suggestion.fitness %></td>                            
  				      <!-- <td class="text-center">
  				            <i class="fa fa-trash"></i>
  				      </td> -->
  					  </tr>
              <% i += 1 %>
  					  <% end %>
					  <% end %>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>